config/routes.rb
Rails.application.routes.draw do
  get 'reserves/index'

  resources :reserves
  get 'reserves/index'
  resources :rooms do
  collection do
    get 'search'
    end
   end
  devise_for :users
  root to: 'rooms#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reserve.rb
class Reserve < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
    belongs_to :user
    has_many :reserves
    has_one_attached :room_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :rooms
  has_many :reserves
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def devise_controller?
  end
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name]) # 新規登録時(sign_up時)にnameというキーのパラメーターを追加で許可する
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/reserves_controller.rb
class ReservesController < ApplicationController
  def index
    @reserves = Reserve.where(user_id: current_user.id )
    @room = Room.all
  end

  def new
    @reserve = Reserve.new
    @room = Room.find(params[:room_id])
  end
 
  def create
    @reserve = Reserve.new(params.require(:reserve).permit(:start_date, :end_date, :number_people, :user_id , :room_id))
        if @reserve.save
          flash[:notice] = "予約が完了をしました"
          redirect_to :reserves
        else
          render "rooms/show"
        end
  end    
 
  def show
  end
 
  def edit
  end
 
  def update
  end
 
  def destroy
    @reserve = Reserve.find(params[:id])
        @reserve.destroy
        flash[:notice] = "投稿を削除しました"
        redirect_to :reserves
  end
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_q, only: [:top, :search]
  
  
  
  def top
  end
  
  def index
    @rooms = Room.where(user_id: current_user.id )
  end
  
  def new
    @room = Room.new
  end
 
  def create
    @room = Room.new(params.require(:room).permit(:room_name, :room_info, :room_price, :room_place, :room_image, :user_id))
      if @room.save
        redirect_to :rooms 
      else
        render "new"
      end
  end
 
  def show
    @room = Room.find(params[:id])
    @reserve = Reserve.new
  end
 
  def edit
  end
  
  def update
  end
 
  def destroy
    @room = Room.find(params[:id])
      @room.destroy
      flash[:notice] = "ユーザーを削除しました"
      redirect_to :rooms
  end
    
  def search
    @results = @q.result
  end
  
  def set_q
    @q = Room.ransack(params[:q])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reserved_helper.rb
module ReservedHelper
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/home/search.html.erb
<h1>検索結果</h1>
<table>
  <thead>
    <tr>
      <th>ルーム画像</th>
      <th>ルーム名</th>
      <th>ルーム紹介</th>
      <th>料金</th>
      <th>住所</th>
      <th>作成日</th>
    </tr>
  </thead>

<tbody>
    <% @results.each do |room| %>
      <tr>
        <td><%= image_tag room.room_image , :size =>'200x150' %></td>
        <td><%= room.room_name %></td>
        <td><%= room.room_info %></td>
        <td><%= room.room_price %></td>
        <td><%= room.room_place %></td>
        <td><%= room.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Top', rooms_path %>

app/views/home/top.html.erb
<h1>Home#top</h1>
<p>Find me in app/views/home/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Share17</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %> 
  <header class="header">
  <%= link_to "poteshare", "/" %>
  <h2>  <%= current_user.name %>  </h2>
  <%= link_to "ルーム登録", :new_room %>
  <%= link_to "登録済みルーム一覧", :rooms  %>
  <%= link_to "予約済みルーム一覧", :reserves  %>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %> 
  </header>
<% else %>
 <header class="header">
  <%= link_to "poteshare", "/" %>
  <%= link_to "ログイン", new_user_session_path, class: 'post' %>
  <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
  </header>
<% end %>
    <%= yield %>
    <footer class="footer">
    <p>© 2020 POTEPAN.INC.</p>
    </footer>
  </body>
</html>

app/views/reserves/complete.html.erb
<h1>予約フォーム</h1>
<p>ご予約ありがとうございました。</p>

app/views/reserves/confirm.html.erb
<h1>予約確認</h1>

<dl>
	<dt>開始日</dt>
	<dd><%= @reserve.start_date %></dd>
	<dt>終了日</dt>
	<dd><%= @reserve.end_date %></dd>
	<dt>予約人数</dt>
	<dd><%= @reserve.nunmber_people %></dd>
</dl>

<%= form_for @reserve, method: :room, url: reserve_back_path do |form| %>
	<%= form.hidden_field :start_date %>
	<%= form.hidden_field :end_date %>
	<%= form.hidden_field :number_people %>
	<%= form.submit '入力画面に戻る' %>
<% end %>
<%= form_for @reserve, method: :room, url: reserve_complete_path do |form| %>
	<%= form.hidden_field :start_date %>
	<%= form.hidden_field :end_date %>
	<%= form.hidden_field :number_people %>
	<%= form.submit '送信する' %>
<% end %>

app/views/reserves/index.html.erb
<h3>予約済みルーム一覧</h3>
 
    <table>
      <thead>
        <tr>
          <th>ルーム画像</th>
          <th>ルーム名</th>
          <th>ルーム紹介</th>
          <th>合計金額</th>
          <th>開始日</th>
          <th>終了日</th>
          <th>予約確定日時</th>
        </tr>
      </thead>
 
      <tbody>
        <% @reserves.each do |reserve| %>
          <tr>
            <td><%= image_tag reserve.room.room_image , :size =>'200x150' %></td>
            <td><%= reserve.room.room_name %></td>
            <td><%= reserve.room.room_info%></td>
            <td><%= reserve.room.room_price %></td>
            <td><%= reserve.start_date %></td>
            <td><%= reserve.end_date %></td>
            <td><%= reserve.created_at %></td>
            <td><%= link_to "削除", reserve, method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
          </tr>
        <% end %>
        
      </tbody>
    </table>

app/views/rooms/index.html.erb
<h3>登録済みルーム一覧</h3>
 
    <table>
      <thead>
        <tr>
          <th>ルーム画像</th>
          <th>ルーム名</th>
          <th>ルーム紹介</th>
          <th>料金</th>
          <th>住所</th>
          <th>作成日</th>
          <th>詳細</th>
          <th>削除</th>
        </tr>
      </thead>
 
      <tbody>
        <% @rooms.each do |room| %>
          <tr>
            <td><%= image_tag room.room_image , :size =>'200x150' %></td>
            <td><%= room.room_name %></td>
            <td><%= room.room_info %></td>
            <td><%= room.room_price %></td>
            <td><%= room.room_place %></td>
            <td><%= room.created_at %></td>
            <td><%= link_to "詳細", room %></td>
            <td><%= link_to "削除", room, method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
 

app/views/rooms/new.html.erb
<h3>ルーム新規作成</h3>
 
    <%= form_with model: @room do |f| %>
      <table>
        <tr>
          <th><%= f.label :room_name ,"ルーム名" %></th>
          <td><%= f.text_field :room_name %></td>
        </tr>
 
        <tr>
          <th><%= f.label :room_info ,"ルーム紹介" %></th>
          <td><%= f.text_area :room_info %></td>
        </tr>
 
        <tr>
          <th><%= f.label :room_price ,"料金" %></th>
          <td><%= f.number_field :room_price , min: 1 %></td>
        </tr>
 
        <tr>
          <th><%= f.label :room_place ,"住所" %></th>
          <td><%= f.text_field :room_place %></td>
        </tr>
        
        <tr>
          <th><%= f.label :room_image ,"ルーム画像" %></th>
          <td><%= f.file_field :room_image %></td>
        </tr>
        <%= f.hidden_field :user_id, value: current_user.id %>
      </table>
      <div>
        <ul>
          <li><%= f.submit "登録完了する"%></li>
          <li><%= link_to "ルーム一覧に戻る", :rooms %></li>
        </ul>
      </div>
    <% end %>

app/views/rooms/seach.html.erb
<h1>検索結果</h1>
<table>
  <thead>
    <tr>
      <th>ルーム画像</th>
      <th>ルーム名</th>
      <th>ルーム紹介</th>
      <th>料金</th>
      <th>住所</th>
      <th>作成日</th>
    </tr>
  </thead>

<tbody>
    <% @results.each do |room| %>
      <tr>
        <td><%= image_tag room.room_image , :size =>'200x150' %></td>
        <td><%= room.room_name %></td>
        <td><%= room.room_info %></td>
        <td><%= room.room_price %></td>
        <td><%= room.room_place %></td>
        <td><%= room.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Top', rooms_path %>

app/views/rooms/show.html.erb
<h3>ルーム詳細</h3>
 
    <table>
      <tr>
        <th>ルーム名</th>
        <td><%= @room.room_name %></td>
      </tr>
      <tr>
        <th>ルーム紹介</th>
        <td><%= @room.room_info %></td>
      </tr>
      <tr>
        <th>値段</th>
        <td><%= @room.room_price %></td>
      </tr>
      <tr>
        <th>住所</th>
        <td><%= @room.room_place %></td>
      </tr>
      <tr>
        <th>ルーム画像</th>
        <td>
          <td><%= image_tag @room.room_image , :size =>'500x400' %></td>
        </td>
      </tr>
    </table>

<h3>ルーム予約</h3>
 
    <%= form_with model: @reserve do |f| %>
      <table>
        <tr>
          <th><%= f.label :start_date ,"開始日" %></th>
          <td><%= f.date_select :start_date %></td>
        </tr>
 
        <tr>
          <th><%= f.label :end_date ,"終了日" %></th>
          <td><%= f.date_select :end_date %></td>
        </tr>
 
        <tr>
          <th><%= f.label :number_people ,"人数" %></th>
          <td><%= f.number_field :unmber_people , min: 1 %></td>
        </tr>
      </table>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :room_id, value: @room.id %>
      <div>
        <ul>
          <li><%= f.submit "予約"%></li>
        </ul>
      </div>
    <% end %>

app/views/rooms/top.html.erb
<div class="top">
    <div class="top-main">
        <div class="container">
            <div class="row col-lg-6">
                <div class="form-fream">
                    <div class="form-area">
                        <p class="form-area-title mb-4">Potepan Shareでまだ体験したことのない旅をしよう</p>
                        <%= search_form_for @q, url: search_rooms_path do |f| %>
                        <%= f.label :room_place, 'エリア' %>
                        <%= f.search_field :room_place %>
                        <br>
                        <%= f.submit '探す' %>
                        <% end %>
                        </form>                    
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="panel-area m-5">
            <h1 class="section-title">おすすめのエリア</h1>
            <div class="row">
                <div class="panel-item col-lg-3 col-6">
                    <span>東京</span>
                    <%= link_to image_tag('https://presite-potepancamp-rails-02.herokuapp.com/assets/img_tokyo.jpg', class: "panel-image"), 'rooms/search' %>
                    <div class="shadow"></div>
                </div>
                <div class="panel-item col-lg-3 col-6">
                    <span>大阪</span>
                    <%= link_to image_tag('https://presite-potepancamp-rails-02.herokuapp.com/assets/img_osaka.jpg', class: "panel-image"), 'rooms/search' %>
                    <div class="shadow"></div>
                </div>
                <div class="panel-item col-lg-3 col-6">
                    <span>京都</span>
                    <%= link_to image_tag('https://presite-potepancamp-rails-02.herokuapp.com/assets/img_kyoto.jpg', class: "panel-image"), 'rooms/search' %>
                    <div class="shadow"></div>
                </div>
                <div class="panel-item col-lg-3 col-6">
                    <span>札幌</span>
                    <%= link_to image_tag('https://presite-potepancamp-rails-02.herokuapp.com/assets/img_sapporo.jpg', class: "panel-image"), 'rooms/search' %>
                    <div class="shadow"></div>
                </div>
            </div>
        </div>
    </div>
</div>